(function(A,b,n,o,y,g,d,p,_,v){"use strict";const{FormText:U,FormSection:M,FormRow:h}=p.Forms;let S;function $(){S??=b.findByStoreName("UserStore"),_.useProxy(o.storage),o.storage.ignore??={users:[],bots:!1};const[r,e]=n.React.useState(o.storage.ignore.users||[]),t=function(s){const i=r.filter(function(c){return c!==s});o.storage.ignore.users=i,e(i),d.showToast("User removed from ignore list",g.getAssetIDByName("Check"))},a=function(){v.showConfirmationAlert({title:"Clear Ignored Users",content:`Remove all ${r.length} users from ignore list?`,confirmText:"Clear",cancelText:"Cancel",onConfirm:function(){o.storage.ignore.users=[],e([]),d.showToast("Cleared all ignored users",g.getAssetIDByName("Check"))}})};return n.React.createElement(n.ReactNative.ScrollView,{style:{flex:1}},n.React.createElement(M,{title:"Settings"},n.React.createElement(h,{label:"Ignore Bots",subLabel:"Don't log messages from bots",trailing:n.React.createElement(p.Forms.FormSwitch,{value:o.storage.ignore.bots,onValueChange:function(s){o.storage.ignore.bots=s}})})),n.React.createElement(M,{title:"Ignored Users"},n.React.createElement(h,{label:"Clear All",subLabel:`${r.length} users ignored`,trailing:n.React.createElement(h.Icon,{source:g.getAssetIDByName("ic_trash_24px")}),onPress:a}),r.length===0?n.React.createElement(U,{style:{padding:10}},"No users ignored."):r.map(function(s){const i=S?.getUser(s)?.username||s;return n.React.createElement(h,{key:s,label:i,trailing:n.React.createElement(n.ReactNative.TouchableOpacity,{onPress:function(){return t(s)}},n.React.createElement(h.Icon,{source:g.getAssetIDByName("ic_close_24px")}))})})))}const T=["UserProfileOverflowMenu","BotUserProfileOverflowMenu"];function R(r){let e=r?.props?.items;return Array.isArray(e)&&Array.isArray(e[0])||(e=r?.props?.children?.props?.items,Array.isArray(e)&&Array.isArray(e[0]))?e[0]:null}function B(r,e){try{const t=r[0]??{},a=t.user?.id;if(!a)return;const s=R(e);if(!s||s.some(function(u){return u?.label==="Ignore User"||u?.label==="Unignore User"}))return;const i=o.storage.ignore?.users?.includes(a),c=s.findIndex(function(u){return u?.isDestructive}),l=c===-1?s.length:c;s.splice(l,0,{label:i?"Unignore User":"Ignore User",isDestructive:!i,action:function(){i?(o.storage.ignore.users=o.storage.ignore.users.filter(function(u){return u!==a}),d.showToast(`Unignored ${t.user?.username||"user"}`)):(o.storage.ignore.users||(o.storage.ignore.users=[]),o.storage.ignore.users.push(a),d.showToast(`Ignoring ${t.user?.username||"user"}`))}})}catch(t){console.error("[MessageLogger] Context menu error:",t)}}function C(){const r=[];for(const e of T){const t=b.findByName(e,!1);t&&r.push(y.after("default",t,B))}return function(){for(const e of r)e()}}let E;const f=[],m=[];o.storage.ignore??={users:[],bots:!1};function I(r){let e=r.content||"";if(r.embeds?.length)for(const t of r.embeds){if(t.title&&(e+=`
${t.title}`),t.description&&(e+=`
${t.description}`),t.fields?.length)for(const a of t.fields)e+=`
${a.name}: ${a.value}`;t.url&&(e+=`
${t.url}`)}if(r.attachments?.length)for(const t of r.attachments)e+=`
\u{1F4CE} ${t.filename} (${Math.round(t.size/1024)}KB)`;return e||"[Empty Message]"}function D(r,e){return`> ${r.replace(/\n/g,`
> `)}

-# ${e}`}var L={onLoad(){try{E=b.findByStoreName("MessageStore"),f.push(y.before("dispatch",n.FluxDispatcher,function(r){const e=r[0];if(e?.type!=="MESSAGE_DELETE"||!e?.id||!e?.channelId)return;const t=E?.getMessage(e.channelId,e.id);if(!t||o.storage.ignore?.users?.includes(t.author?.id)||o.storage.ignore?.bots&&t.author?.bot)return;if(m.includes(e.id)){m.splice(m.indexOf(e.id),1);return}m.push(e.id);const a=I(t),s=n.moment().format("HH:mm:ss");r[0]={type:"MESSAGE_EDIT_FAILED_AUTOMOD",messageData:{type:1,message:{channelId:e.channelId,messageId:e.id}},errorResponseBody:{code:2e5,message:D(a,s)}}})),f.push(y.before("dispatch",n.FluxDispatcher,function(r){const e=r[0];if(e?.type!=="MESSAGE_DELETE_BULK"||!e?.ids?.length||!e?.channelId)return;const t=[];for(const c of e.ids){const l=E?.getMessage(e.channelId,c);l&&(o.storage.ignore?.users?.includes(l.author?.id)||o.storage.ignore?.bots&&l.author?.bot||t.push(l))}if(t.length===0)return;let a=`**${t.length} messages deleted:**

`;for(const c of t){const l=c.author?.username||"Unknown",u=I(c);a+=`**${l}**: ${u}
`}const s=n.moment().format("HH:mm:ss"),i=t[0]?.id||e.ids[0];r[0]={type:"MESSAGE_EDIT_FAILED_AUTOMOD",messageData:{type:1,message:{channelId:e.channelId,messageId:i}},errorResponseBody:{code:2e5,message:D(a.trim(),s)}}})),f.push(y.before("dispatch",n.FluxDispatcher,function(r){const e=r[0];if(e?.type!=="MESSAGE_UPDATE"||!e?.message)return;const t=e.message;if(!t.id||!t.channel_id||o.storage.ignore?.users?.includes(t.author?.id)||o.storage.ignore?.bots&&t.author?.bot)return;const a=E?.getMessage(t.channel_id,t.id);if(!a)return;const s=I(a),i=I(t);if(s===i)return;const c=n.moment().format("HH:mm:ss"),l=`**Before:**
${s}

**After:**
${i}`;r[0]={type:"MESSAGE_EDIT_FAILED_AUTOMOD",messageData:{type:1,message:{channelId:t.channel_id,messageId:t.id}},errorResponseBody:{code:2e5,message:D(l,c)}}})),f.push(C()),d.showToast("Message Logger loaded",g.getAssetIDByName("Check"))}catch(r){console.error("[MessageLogger] Load error:",r),d.showToast("Failed to load Message Logger",g.getAssetIDByName("Small"))}},onUnload(){for(const r of f)try{r()}catch{}f.length=0,m.length=0,d.showToast("Message Logger unloaded",g.getAssetIDByName("Check"))},settings:$};return A.default=L,Object.defineProperty(A,"__esModule",{value:!0}),A})({},vendetta.metro,vendetta.metro.common,vendetta.plugin,vendetta.patcher,vendetta.ui.assets,vendetta.ui.toasts,vendetta.ui.components,vendetta.storage,vendetta.ui.alerts);
